src/Entity/ProductReference.php
<?php

namespace App\Entity;

use App\Entity\Trait as HelperTrait;
use App\Repository\ProductReferenceRepository;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: ProductReferenceRepository::class)]
/**
 * @author Aléki <alexlegras@hotmail.com>
 * @version 1
 * This class represent a reference of product, this class can be bind in Product Class to describe it's price and weight.
 * This is class use Lifecycle callback throught traits.
 */
class ProductReference 
{
    use HelperTrait\TimestampableWithIdTrait;
    use HelperTrait\SluggableTrait;
    use HelperTrait\DeletableTrait;

    #[Assert\NotNull]
    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $price = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $weight = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $weightType = null;

    #[ORM\JoinColumn(nullable: false)]
    #[ORM\ManyToOne(inversedBy: 'productReferences')]
    private ?Product $product = null;
    
    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true, type: Types::STRING)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true, type: Types::INTEGER)]
    private ?int $imageSize = null;

    /**
     * Price getter
     *
     * @return integer|null
     */
    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice(): ?float {
        return $this->getPrice()/100;
    }

    /**
     * Price setter
     *
     * @param integer $price
     * @return static
     */
    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Weight getter
     *
     * @return integer|null
     */
    public function getWeight(): ?int
    {
        return $this->weight;
    }

    /**
     * Weight setter
     *
     * @param integer|null $weight
     * @return static
     */
    public function setWeight(?int $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * Weight type getter , represent the unit of product reference weight 
     * example : g, mg , L, mL
     *
     * @return string|null
     */
    public function getWeightType(): ?string
    {
        return $this->weightType;
    }

    /**
     * Weight type setter
     *
     * @param string|null $weightType
     * @return static
     */
    public function setWeightType(?string $weightType): static
    {
        $this->weightType = $weightType;

        return $this;
    }

    /**
     * Retrieve the parent product associated with this reference.
     *
     * This method is useful when you need to access the parent product of a reference.
     *
     * @return Product|null
     */
    public function getProduct(): ?Product
    {
        return $this->product;
    }

    /**
     * Bind product
     *
     * @param Product|null $product
     * @return static
     */
    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }


    /**
     * Method use by SluggableTrait to get valid source to slug
     *
     * @return string
     */
    public function getValueToSlugify(): string {
        return "{$this->product->getName()} {$this->weight}{$this->weightType}";
    }


    /**
     * return a string with weight and weight type of a reference 
     *
     * @return string
     */
    public function toString() : string {
        return "{$this->getWeight()} {$this->getWeightType()}";
    }


      /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    /**
     * Getter for a ImageFile attribute
     *
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * Setter for a imageName attribute
     *
     * @param string|null $imageName
     * @return void
     */
    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    /**
     * Getter for a imageName attribute
     *
     * @return string|null
     */
    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * Setter for a imageSize attribute
     *
     * @param integer|null $imageSize
     * @return void
     */
    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    /**
     * Getter for a imageSize attribute
     *
     * @return integer|null
     */
    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    /**
     * Virtual property , retreive image path
     *
     * @return string
     */
    public function getImageUrl() : string {
        return sprintf("/images/products/%s", $this->imageName ?? '');
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @author Aléki <alexlegras@hotmail.com>
 * @version 1
 * Controller that handle home routes
 */
class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    /**
     * Render home view to client
     *
     * @return Response
     */
    public function index(EntityManagerInterface $manager): Response
    {
        $products = $manager->getRepository(Product::class)->getSelectionProductWithoutSoftDelete();
        return $this->render('home/index.html.twig', [
            'selection' => $products
        ]);
    }

    /**
     * Render view with all product from DB
     *
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/nos-produits', name:'home.products')]
    public function products() : Response{
        return $this->render('home/products.html.twig');
    }

    #[Route('/politique-confidentialite', name: 'home.privacy')]
    public function privacyPolicy(){
        return $this->render('home/privacy.html.twig');
    }

}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	- Accueil
{% endblock %}

{% block body %}
	<div class="sm:mb-10 sm:h-full">
		<div class="relative flex justify-center items-center my-2">
			<img src="/hero.jpeg" alt="" class="w-4/6 lg:w-1/2 rounded-md shadow-lg">
			<h1 class="absolute text-4xl lg:text-6xl text-center font-extralight text-white">Bienvenue sur{{app_name}}</h1>
		</div>
		<div class="mt-4 ml-10 space-y-10">
			<h2 class="my-5 text-4xl font-extralight text-black">Comment commander vos confitures ?</h2>
			<div class="grid grid-cols-3 mx-4">
				<div class="ml-8">
					<h4 class="text-2xl text-semibold">1.Choisissez vos produits</h4>
					<p class="my-4 ml-4 text-gray-600 text-justify">
						Vous pouvez choisir
						<a href="{{path('home.products')}}" class="border rounded-md px-3 mr-1 py-0.5 bg-purplemecha-500 text-white hover:bg-white hover:border-purplemecha-500 hover:border-2 hover:text-purplemecha-500">
							vos produits
						</a>
						et faire une demande de commande.
					</p>

				</div>
				<div class="ml-8">
					<h4 class="text-2xl text-semibold">2.On se retrouve</h4>
					<p class="my-4 ml-4 text-gray-600 text-justify">
						Après avoir passé votre commande nous fixons un point de rendez-vous où vous pouvez venir la récupérer.
												Ou alors passer par d'autres intermédiaires en fonction de la distance et ainsi éviter trop de frais pour tout le monde.
					</p>
				</div>
				<div class="ml-8">
					<h4 class="text-2xl text-semibold">3.On se régale</h4>
					<p class="my-4 ml-4 text-gray-600 text-justify">
						Bonne dégustation, n'hésiter pas à me faire des retours !
					</p>
				</div>
			</div>
		</div>
		<hr class="my-8 mx-10">
		<div class="mt-4">
			<div class="flex">
				<h2 class="ml-10 my-5 text-4xl font-extralight text-black">Découvrer notre sélection</h2>
				<a href="/nos-produits" class="px-2 py-1 bg-purplemecha-500 h-1/2 mt-6 ml-5 text-white rounded-md hover:font-bold text-center">
					Voir tous nos produits
					<i class="fa-regular fa-square-plus ml-2"></i>
				</a>
			</div>
			<div class="flex justify-center mx-5">
				<div class="grid grid-cols-3 lg:grid-cols-4 gap-10 w-5/6">
					{% for item in selection %}
						<div>
							<img src="{{ item.productReferences[0].imageUrl }}" class="w-full rounded-xl shadow-lg" alt="">
							<h4 class="text-xl font-light my-4">
								{{ item.name }}
							</h4>
							<button class="rounded-md text-gray-600 hover:text-gray-800 hover:font-semibold px-2 text-center">
								À partir de
								{{ item.productReferences[0].formatedPrice|number_format(2) }}
								€
							</button>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>


		{# Etape pour commander des confitures #}
	{# <div class="mt-5 h-fit">
													<h2 class="text-4xl text-[#4C7C80] text-center my-10">Comment acheter de bonnes confitures ?</h2>
													<div class="grid grid-cols-3 lg:grid-cols-5 lg:gap-10 gap-4 sm:px-5">
														<div class="lg:col-start-2 rounded border-2 border-orange-900 bg-[#80504C]/5 px-4 py-2 break-words">
															<h4 class="sm:h-20 sm:text-center ml-3 text-orange-900 text-2xl">
																<span class="text-[#804C62] text-2xl mr-2">1.</span>Choisissez vos produits
															</h4>
															<div class="h-64">
																<p class="px-1 text-[#4C7C80] mt-2 text-lg font-medium leading-relaxed">
																	Vous pouvez choisir vos produits et faire une demande de commande ici:
																</p>
																<div class="text-center mt-4">
																	<a href="{{path('home.products')}}" class="border rounded-md px-3 py-2 bg-[#804C62] text-white hover:bg-white hover:border-[#804C62] hover:border-2 hover:text-[#804C62]" href="route produit">
																		Découvrir les produits !
																	</a>
																</div>
															</div>
															<img src="/click-demo.png" alt="">
														</div>
														<div class="rounded border-2 border-orange-900 bg-[#80504C]/10 px-4 py-2">
															<h4 class="sm:h-20 sm:text-center ml-3 text-orange-900 text-2xl">
																<span class="text-[#804C62] text-2xl mr-2">2.</span>On se retrouve
															</h4>
															<div class="h-64">
																<p class="px-1 text-[#4C7C80] mt-2 text-lg font-medium leading-relaxed">
																	Après avoir passé votre commande nous fixons un point de rendez-vous où vous pouvez venir la récupérer.
																	Ou alors passer par d'autres intermédiaires en fonction de la distance et ainsi éviter trop de frais pour tout le monde.
																</p>
															</div>
															<img src="/handshake-demo.png" alt="">
														</div>
														<div class="rounded border-2 border-orange-900 bg-[#80504C]/20 px-4 py-2">
															<h4 class="sm:h-20 sm:text-center ml-3 text-orange-900 text-2xl">
																<span class="text-[#804C62] text-2xl mr-2">3.</span>On se régale
															</h4>
															<div class="h-64">
																<p class="px-1 text-[#4C7C80] mt-2 text-lg font-medium leading-relaxed">
																	Bonne dégustation, n'hésiter pas à me faire des retours !
																</p>
															</div>
															<img src="/smiley-demo.png" alt="">
														</div>
													</div>
												</div> #}
		{# <h2 class="text-4xl text-[#4C7C80] text-center my-10 underline">Nos valeurs</h2>
																						<hr class="my-5 mx-40">
																				
																						<div class="px-10 my-10 leading-relaxed">
																							<h3 class="text-3xl text-[#804C62] my-5 font-bold text-center">
																								⦿ On suit les saisons !</h3>
																							<p class="px-10 sm:text-xl">
																								Toutes les confitures et gelées sont faites avec des fruits de saisons. Fraises, abricots, pêches et prunes l'été. Des pommes, des mûres à la fin de l'été et à l'arrivée de l'automne.
																																								Des agrumes et de l'ananas l'hiver puisque ceux-ci viennent des pays chauds à cette période de l'année. Même chose pour les compotes et les jus de pommes qui arrivent en automne-hiver.
																																								 L'avantage des confitures et gelées c'est qu'elles peuvent être consommées à n'importe quel moment de l'année et se conserver longtemps (mais ça vaut aussi pour les autres produits que je propose :) ). 
																																								Tous les fruits sont selectionnés et choisis à maturité pour le goût. Bien entendu vous pouvez retrouver toute l'année confitures de lait et sauces au caramel.
																							</p>
																						</div>
																						<hr class="my-5 mx-40">
																						<div class="my-10 px-6 lg:px-20">
																							<h3 class="text-3xl text-[#804C62] my-5 font-bold text-center">
																								⦿ On fait ça bien !
																							</h3>
																							<div class="grid grid-cols-1 lg:grid-cols-6 gap-6 items-center">
																								<div class="lg:col-span-2 flex justify-center">
																									<img src="/jelly_5184x3456.jpeg" class="rounded-lg shadow-lg max-w-full h-auto" alt="Photo de confiture en préparation">
																								</div>
																								<div class="lg:col-span-4 text-justify">
																									<p class="text-lg lg:text-xl leading-relaxed text-gray-700">
																										Les confitures sont faites dans des bassines en cuivre, tout est fait à la main pour la meilleure qualité possible. Rien n'est ajouté dans aucun des produits, ni colorant ni gélifiant. 
																																												Ce serait dommage de modifier le goût des fruits. De même pour la confiture de lait, qui est très belle comme elle est.
																																												Je réalise mes produits dans le respect de la tradition familiale et sans conservateurs.
																									</p>
																								</div>
																							</div>
																						</div>
																						<hr class="my-5 mx-40">
																						<div class="mt-10 px-10">
																							<h3 class="text-3xl text-[#804C62] my-5 font-bold text-center">
																								⦿ On pense au tri !</h3>
																							<p class="px-10 sm:text-xl">
																								Pour préserver l'environnement tous les pots, les bocaux et les bouteilles ne sont plus consignés mais vous avez toujours la possibilité de me les ramener. 
																																								De cette manière on limite la production de verre. De plus je propose des sacs à 20 centimes pour vous faciliter la tâche. Il vous suffit de me le préciser. 
																																								L'idéal serait d'amener votre propre sac afin de limiter les déchets. Vous avez tous les moyens pour me contacter dans l'onglet "contact".
																							</p>
																						</div>
																						<hr class="my-10 mx-10">
																						<h2 class="text-4xl text-[#4C7C80] text-center my-10">Suivez-nous</h2>
																						<div class="mt-10 px-10">
																							<p class="px-10 sm:text-xl">
																								Retrouvez-moi sur les réseaux sociaux. Vous pouvez suivre l'actualité que je poste sur ma page facebook et sur mon compte instagram. Différents évènements pourront apparaître (portes ouvertes etc...).
																																								Je vous informerai des nouveautés.
																							</p>
																							<div class="flex justify-center my-5">
																								<a href="https://www.facebook.com/Gout-m%C3%A9-cha-104158378103823" class="hover:text-[#4C7C80] [&>svg]:h-16 [&>svg]:w-16">
																									<svg class="" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewbox="0 0 320 512">
																										<path d="M80 299.3V512H196V299.3h86.5l18-97.8H196V166.9c0-51.7 20.3-71.5 72.7-71.5c16.3 0 29.4 .4 37 1.2V7.9C291.4 4 256.4 0 236.2 0C129.3 0 80 50.5 80 159.4v42.1H14v97.8H80z"/>
																									</svg>
																								</a>
																								<a href="https://www.instagram.com/goutmecha/" class="me-6 hover:text-[#4C7C80w] [&>svg]:h-16 [&>svg]:w-16">
																									<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewbox="0 0 448 512">
																										<path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/>
																									</svg>
																								</a>
																							</div>
																						</div> #}
	</div>
{% endblock %}

templates/home/privacy.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Politique de Confidentialité
{% endblock %}

{% block body %}
<div class="max-w-4xl mx-auto py-8 px-4 sm:h-screen">
    <h1 class="text-3xl font-bold mb-6 text-[#804C62]">Politique de Confidentialité</h1>

    <p class="mb-4 ml-5">
        Votre vie privée est importante pour nous. Cette politique de confidentialité explique quelles informations personnelles nous collectons et comment nous les utilisons.
    </p>

    <h2 class="text-2xl font-semibold mb-4 text-[#804C62]">Informations que nous collectons</h2>
    <p class="mb-4 ml-5">
        Nous collectons les informations suivantes :
    </p>
    <ul class="list-disc list-inside mb-4 ml-5">
        <li>Nom</li>
        <li>Prénom</li>
        <li>Email</li>
    </ul>

    <h2 class="text-2xl font-semibold mb-4 text-[#804C62]">Utilisation des informations</h2>
    <p class="mb-4 ml-5">
        Les informations que nous collectons sont utilisées pour les finalités suivantes :
    </p>
    <ul class="list-disc list-inside mb-4 ml-5">
        <li>Gestion des commandes</li>
        <li>Communication avec les clients</li>
    </ul>

    <h2 class="text-2xl font-semibold mb-4 text-[#804C62]">Sécurité des données</h2>
    <p class="mb-4 ml-5">
        Nous mettons en œuvre des mesures de sécurité pour protéger vos informations personnelles. Les données sont stockées de manière sécurisée et accessibles uniquement aux personnes autorisées.
    </p>

    <h2 class="text-2xl font-semibold mb-4 text-[#804C62]">Vos droits</h2>
    <p class="mb-4 ml-5">
        Conformément au RGPD, vous avez les droits suivants concernant vos données personnelles :
    </p>
    <ul class="list-disc list-inside mb-4 ml-5">
        <li>Droit d'accès</li>
        <li>Droit de rectification</li>
        <li>Droit à l'effacement</li>
        <li>Droit à la portabilité</li>
        <li>Droit d'opposition</li>
    </ul>
    <p class="mb-4 ml-5">
        Pour exercer ces droits, vous pouvez nous contacter à l'adresse suivante : <strong>goutmecha@gmail.com</strong>.
    </p>

    <h2 class="text-2xl font-semibold mb-4 text-[#804C62]">Contact</h2>
    <p class="mb-4 ml-5">
        Si vous avez des questions concernant cette politique de confidentialité, vous pouvez nous contacter à l'adresse suivante : <strong>goutmecha@gmail.com</strong>.
    </p>
</div>
{% endblock %}

templates/home/products.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	- Nos produits
{% endblock %}

{% block body %}
    <div class="my-10 mx-10" {{ vue_component('products/grid') }}></div>
{% endblock %}